services:
  - type: web
    env: ruby
    name: zoey-web
    region: ohio
    plan: starter
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    autoDeploy: true
    # domains:
    #   - 'zoey.so'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zoe-db
          property: connectionString
      - fromGroup: zoey-shared
databases:
  - name: zoey-db
    region: ohio
    plan: starter
    ipAllowList: []
envVarGroups:
  - name: zoey-shared
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: OPENAI_TOKEN
        sync: false
